package com.test1.PlantsVsZombies.src.Enums;

public enum PlantType {
    SUNFLOWER("SUNFLOWER", "IMAGE_UI_SUNFLOWER", "768/INITIAL/PLANT/SUNFLOWER/SUNFLOWER.PAM", "idle"),
    TWIN_SUNFLOWER("TWIN_SUNFLOWER", "IMAGE_UI_PACKETS_TWINSUNFLOWER", "768/INITIAL/PLANT/SUNFLOWER_TWIN/SUNFLOWER_TWIN.PAM", "idle"),
    SUN_SHROOM("SUN_SHROOM", "IMAGE_UI_PACKETS_SUNSHROOM", "768/FULL/PLANT/SUNSHROOM/SUNSHROOM.PAM", "idle_stage2"),
    PRIMAL_SUNFLOWER("PRIMAL_SUNFLOWER", "IMAGE_UI_PACKETS_PRIMALSUNFLOWER", "768/FULL/PLANT/PRIMAL_SUNFLOWER/PRIMAL_SUNFLOWER.PAM", "idle"),
    GOLD_BLOOM("GOLD_BLOOM", "IMAGE_UI_PACKETS_GOLDBLOOM", "768/INITIAL/PLANT/GOLDBLOOM/GOLDBLOOM.PAM", "idle"),
    PEASHOOTER("PEASHOOTER", "IMAGE_UI_PACKETS_PEASHOOTER", "768/INITIAL/PLANT/PEASHOOTER/PEASHOOTER.PAM", "idle"),
    REPEATER("REPEATER", "IMAGE_UI_PACKETS_REPEATER", "768/INITIAL/PLANT/REPEATER/REPEATER.PAM", "idle"),
    THREEPEATER("THREEPEATER", "IMAGE_UI_PACKETS_THREEPEATER", "768/INITIAL/PLANT/THREEPEATER/THREEPEATER.PAM", "idle"),
    SNOW_PEA("SNOW_PEA", "IMAGE_UI_HUD_LOD_LOD_SNOWPEA", "768/INITIAL/PLANT/SNOWPEA/SNOWPEA.PAM", "idle"),
    ROTOBAGA("ROTOBAGA", "IMAGE_UI_PACKETS_XSHOT", "768/FULL/PLANT/ROTORUTABAGA/ROTORUTABAGA.PAM", "idle"),
    PEA_POD("PEA_POD", "IMAGE_UI_PACKETS_PEAPOD", "768/FULL/PLANT/PEAPOD/PEAPOD.PAM", "idle"),
    SPLIT_PEA("SPLIT_PEA", "IMAGE_UI_PACKETS_SPLITPEA", "768/FULL/PLANT/SPLITPEA/SPLITPEA.PAM", "idle"),
    CITRON("CITRON", "IMAGE_UI_PACKETS_CITRON", "768/FULL/PLANT/CITRON/CITRON.PAM", "idle"),
    CAULIPOWER("CAULIPOWER", "IMAGE_UI_PACKETS_CAULIPOWER", "768/INITIAL/PLANT/CAULIPOWER/CAULIPOWER.PAM", "idle4_1"),
    ELECTRIC_BLUEBERRY("ELECTRIC_BLUEBERRY", "IMAGE_UI_PACKETS_ELECTRICBLUEBERRY", "768/INITIAL/PLANT/ELECTRICBLUEBERRY/ELECTRICBLUEBERRY.PAM", "idle2_1"),
    BOWLING_BULB("BOWLING_BULB", "IMAGE_UI_PACKETS_BOWLINGBULB", "768/FULL/PLANT/BOWLINGBULB/BOWLINGBULB.PAM", "idle"),
    CACTUS("CACTUS", "IMAGE_UI_HUD_LOD_LOD_CACTUS", "768/INITIAL/PLANT/CACTUS/CACTUS.PAM", "idle"),
    FIRE_PEASHOOTER("FIRE_PEASHOOTER", "IMAGE_UI_PACKETS_FIREPEASHOOTER", "768/INITIAL/PLANT/FIREPEASHOOTER/FIREPEASHOOTER.PAM", "idle"),
    STARFRUIT("STARFRUIT", "IMAGE_UI_PACKETS_STARFRUIT", "768/INITIAL/PLANT/STARFRUIT/STARFRUIT.PAM", "idle"),
    GOO_PEASHOOTER("GOO_PEASHOOTER", "IMAGE_UI_PACKETS_POISONPEASHOOTER", "768/INITIAL/PLANT/GOOPEASHOOTER/GOOPEASHOOTER.PAM", "idle"),
    MEGA_GATLING_PEA("MEGA_GATLING_PEA", "IMAGE_UI_PACKETS_MEGAGATLING", "768/INITIAL/PLANT/MEGAGATLING/MEGAGATLING.PAM","idle"),
    SEA_SHROOM("SEA_SHROOM", "IMAGE_UI_PACKETS_SEASHROOM", "768/FULL/PLANT/SEASHROOM/SEASHROOM.PAM", "idle"),
    PUFF_SHROOM("PUFF_SHROOM", "IMAGE_UI_PACKETS_PUFFSHROOM", "768/INITIAL/PLANT/PUFFSHROOM/PUFFSHROOM.PAM", "idle_stage2"),
    FUME_SHROOM("FUME_SHROOM", "IMAGE_UI_PACKETS_FUMESHROOM", "768/INITIAL/PLANT/FUMESHROOM/FUMESHROOM.PAM", "idle"),
    CABBAGE_PULT("CABBAGE_PULT", "IMAGE_UI_PACKETS_CABBAGEPULT", "768/INITIAL/PLANT/CABBAGEPULT/CABBAGEPULT.PAM", "idle"),
    KERNEL_PULT("KERNEL_PULT", "IMAGE_UI_PACKETS_KERNELPULT", "768/INITIAL/PLANT/KERNALPULT/KERNALPULT.PAM", "idle"),
    MELON_PULT("MELON_PULT", "IMAGE_UI_PACKETS_MELONPULT", "768/INITIAL/PLANT/MELONPULT/MELONPULT.PAM", "idle"),
    WINTER_MELON("WINTER_MELON", "IMAGE_UI_PACKETS_WINTERMELON", "768/FULL/PLANT/WINTERMELON/WINTERMELON.PAM", "idle"),
    PEPPER_PULT("PEPPER_PULT", "IMAGE_UI_PACKETS_PEPPERPULT","768/FULL/PLANT/PEPPERPULT/PEPPERPULT.PAM", "idle"),
    POTATO_MINE("POTATO_MINE", "IMAGE_UI_PACKETS_POTATOMINE", "768/INITIAL/PLANT/POTATOMINE/POTATOMINE.PAM", "idle"),
    PRIMAL_POTATO_MINE("PRIMAL_POTATO_MINE", "IMAGE_UI_PACKETS_PRIMALPOTATOMINE", "768/FULL/PLANT/PRIMAL_POTATOMINE/PRIMAL_POTATOMINE.PAM", "idle"),
    CHERRY_BOMB("CHERRY_BOMB", "IMAGE_UI_PACKETS_CHERRY_BOMB", "768/FULL/PLANT/CHERRYBOMB/CHERRYBOMB.PAM", "idle"),
    SQUASH("SQUASH", "IMAGE_UI_PACKETS_SQUASH", "768/INITIAL/PLANT/SQUASH/SQUASH.PAM", "idle"),
    GRAPESHOT("GRAPESHOT", "IMAGE_UI_PACKETS_GRAPESHOT", "768/INITIAL/PLANT/GRAPESHOT/GRAPESHOT.PAM", "idle"),
    JALAPENO("JALAPENO", "IMAGE_UI_PACKETS_JALAPENO", "768/INITIAL/PLANT/JALAPENO/JALAPENO.PAM", "idle"),
    DOOM_SHROOM("DOOM_SHROOM", "IMAGE_UI_PACKETS_DOOMSHROOM", "768/FULL/PLANT/DOOMSHROOM/DOOMSHROOM.PAM", "stage1_idle"),
    TANGLE_KELP("TANGLE_KELP", "IMAGE_UI_PACKETS_TANGLEKELP", "768/FULL/PLANT/TANGLEKELP/TANGLEKELP.PAM", "idle"),
    ICEBERG_LETTUCE("ICEBERG_LETTUCE", "IMAGE_UI_PACKETS_ICEBURG", "768/INITIAL/PLANT/ICEBURG/ICEBURG.PAM", "idle"),
    BONK_CHOY("BONK_CHOY", "IMAGE_UI_PACKETS_BONKCHOY", "768/INITIAL/PLANT/BONKCHOY/BONKCHOY.PAM", "idle"),
    PHAT_BEET("PHAT_BEET", "IMAGE_UI_PACKETS_PHATBEET","768/FULL/PLANT/PHATBEETS/PHATBEETS.PAM", "idle"),
    CHOMPER("CHOMPER", "IMAGE_UI_HUD_LOD_LOD_CHOMPER", "768/INITIAL/PLANT/CHOMPER/CHOMPER.PAM", "idle"),
    WASABI_WHIP("WASABI_WHIP", "IMAGE_UI_HUD_LOD_LOD_TIMETWISTER_WASABI", "768/INITIAL/PLANT/WASABIWHIP/WASABIWHIP.PAM", "idle"),
    KIWIBEAST("KIWIBEAST", "IMAGE_UI_PACKETS_KIWIBEAST", "768/INITIAL/PLANT/KIWIBEAST/KIWIBEAST.PAM", "idle_stage1_"),
    WALL_NUT("WALL_NUT", "IMAGE_UI_PACKETS_WALLNUT", "768/INITIAL/PLANT/WALLNUT/WALLNUT.PAM", "idle"),
    TALL_NUT("TALL_NUT", "IMAGE_UI_PACKETS_TALLNUT", "768/FULL/PLANT/TALLNUT/TALLNUT.PAM","idle"),
    ENDURIAN("ENDURIAN", "IMAGE_UI_PACKETS_ENDURIAN", "768/FULL/PLANT/ENDURIAN/ENDURIAN.PAM", "idle"),
    GARLIC("GARLIC", "IMAGE_UI_PACKETS_GARLIC","768/FULL/PLANT/GARLIC/GARLIC.PAM", "idle"),
    SWEET_POTATO("SWEET_POTATO", "IMAGE_UI_PACKETS_SWEETPOTATO","768/INITIAL/PLANT/SWEETPOTATO/SWEETPOTATO.PAM", "idle"),
    EXPLODE_O_NUT("EXPLODE_O_NUT", "IMAGE_UI_HUD_LOD_LOD_EXPLODEONUT","768/INITIAL/PLANT/EXPLODEONUT/EXPLODEONUT.PAM","idle2"),
    PUMPKIN("PUMPKIN", "IMAGE_PLANT_PUMPKIN_PUMPKIN_179X86","768/INITIAL/PLANT/PUMPKIN/PUMPKIN.PAM", "idle"),
    SUN_BEAN("SUN_BEAN", "IMAGE_UI_PACKETS_SUNBEAN","768/FULL/PLANT/SUNBEAN/SUNBEAN.PAM", "idle"),
    TORCHWOOD("TORCHWOOD", "IMAGE_UI_PACKETS_TORCHWOOD", "768/INITIAL/PLANT/TORCHWOOD/TORCHWOOD.PAM", "idle"),
    MAGNET_SHROOM("MAGNET_SHROOM", "IMAGE_UI_PACKETS_MAGNETSHROOM", "768/FULL/PLANT/MAGNETSHROOM/MAGNETSHROOM.PAM", "idle"),
    HYPNO_SHROOM("HYPNO_SHROOM", "IMAGE_UI_PACKETS_HYPNOSHROOM", "768/INITIAL/PLANT/HYPNOSHROOM/HYPNOSHROOM.PAM", "idle"),
    HOMING_THISTLE("HOMING_THISTLE", "IMAGE_UI_PACKETS_HOMINGTHISTLE", "768/INITIAL/PLANT/HOMINGTHISTLE/HOMINGTHISTLE.PAM", "idle"),
    IMITATER("IMITATER", "IMAGE_UI_PACKETS_IMITATER", "768/INITIAL/PLANT/IMITATER/IMITATER.PAM", "idle"),
    ICE_SHROOM("ICE_SHROOM", "IMAGE_UI_PACKETS_ICESHROOM", "768/FULL/PLANT/ICESHROOM/ICESHROOM.PAM", "idle"),
    LILY_PAD("LILY_PAD", "IMAGE_UI_PACKETS_LILYPAD", "768/FULL/PLANT/LILYPAD/LILYPAD.PAM", "idle2"),
    HOT_POTATO("HOT_POTATO", "IMAGE_UI_PACKETS_HOTPOTATO", "768/FULL/PLANT/HOTPOTATO/HOTPOTATO.PAM", "idle"),
    GRAVE_BUSTER("GRAVE_BUSTER", "IMAGE_UI_PACKETS_GRAVEBUSTER", "768/INITIAL/PLANT/GRAVEBUSTER/GRAVEBUSTER.PAM", "water"),
    ENLIGHTEN_MINT("ENLIGHTEN_MINT", "IMAGE_UI_PACKETS_ENLIGHTENMINT", "768/INITIAL/EMPOWERMINTS/PLANT/ENLIGHTENMINT/ENLIGHTENMINT.PAM", "loop"),
    APPEASE_MINT("APPEASE_MINT", "IMAGE_UI_PACKETS_APPEASEMINT", "768/INITIAL/EMPOWERMINTS/PLANT/APPEASEMINT/APPEASEMINT.PAM", "loop"),
    ARMA_MINT("ARMA_MINT", "IMAGE_UI_PACKETS_ARMAMINT", "768/INITIAL/EMPOWERMINTS/PLANT/ARMAMINT/ARMAMINT.PAM", "loop"),
    BOMBARD_MINT("BOMBARD_MINT", "IMAGE_UI_PACKETS_BOMBARDMINT", "768/INITIAL/EMPOWERMINTS/PLANT/BOMBARDMINT/BOMBARDMINT.PAM", "loop"),
    ENFORCE_MINT("ENFORCE_MINT", "IMAGE_UI_PACKETS_ENFORCEMINT", "768/INITIAL/EMPOWERMINTS/PLANT/ENFORCEMINT/ENFORCEMINT.PAM","loop"),
    REINFORCE_MINT("REINFORCE_MINT", "IMAGE_UI_PACKETS_REINFORCEMINT", "768/INITIAL/EMPOWERMINTS/PLANT/REINFORCEMINT/REINFORCEMINT.PAM", "loop"),
    ENCHANT_MINT("ENCHANT_MINT","IMAGE_UI_PACKETS_ENCHANTMINT", "768/INITIAL/EMPOWERMINTS/PLANT/ENCHANTMINT/ENCHANTMINT.PAM", "loop"),
//    PIERCE_MINT("PIERCE_MINT"),
//    CATTAIL_MINT("CATTAIL_MINT"),
    MARIGOLD("MARIGOLD", "IMAGE_UI_PACKETS_MARIGOLD", "768/INITIAL/PLANT/MARIGOLD/MARIGOLD.PAM", "idle");

    private final String name;
    private final String iconAssetId;
    private final String idleAnimationPath;
    private final String stateName;

    /**
     * Default constructor: derives the collection-screen icon asset id and
     * the idle-animation PAM path from the plant's name using a consistent
     * convention. If your real TextureBank keys or PAM paths for a specific
     * plant don't follow this pattern, use the 3-arg constructor on that
     * one entry to override it explicitly.
     */
    PlantType(String name) {
        this(name, "IMAGE_REWARD_ICON_" + name, "768/INITIAL/PLANT/" + name + "/" + name + ".PAM", "idle");
    }

    PlantType(String name, String iconAssetId, String idleAnimationPath, String stateName) {
        this.name = name;
        this.iconAssetId = iconAssetId;
        this.idleAnimationPath = idleAnimationPath;
        this.stateName = stateName;
    }

    public String getStateName() {
        return stateName;
    }

    public static PlantType fromName(String name) {
        for (PlantType type : values()) {
            if (type.name.equalsIgnoreCase(name)) {
                return type;
            }
        }
        return null;
    }

    public String getName() {
        return name;
    }

    /**
     * Asset id for the thumbnail shown in the Collection screen grid.
     * See constructor javadoc re: placeholder convention.
     */
    public String getIconAssetId() {
        return iconAssetId;
    }

    /**
     * PAM animation path for the idle animation shown in the plant's
     * detail box on the Collection screen.
     */
    public String getIdleAnimationPath() {
        return idleAnimationPath;
    }
}
