package src.Enums;

public enum QuestEvent {
    ZOMBIE_KILLED,
    SUN_COLLECTED,
    PLANT_PLANTED,
    PLANT_REMOVED,
    PLANT_DESTROYED,
    WAVE_COMPLETED,
    LEVEL_WON,
    LEVEL_LOST,
    PLANT_FOOD_USED,
    MOWER_TRIGGERED,
    GAME_STARTED,
    GAME_ENDED,
    EXPLOSIVE_USED,
    SYMMETRY_CHECK,
    FAMILY_USED,
    COLUMN_EMPTY,
    ROW_EMPTY,
    CROSS_EMPTY
}